import express from "express";
import authRoute from "./modules/auth/auth.route";
import photoRoute from "./modules/photo/photo.route";
import userRoute from "./modules/user/user.route";
import organizationRoute from "./modules/organization/organization.route";
import electionRoute from "./modules/election/election.route";
import candidateRoute from "./modules/candidate/candidate.route";
import positionRoute from "./modules/position/position.route";
import voterRoute from "./modules/voter/voter.route";
import partyRoute from "./modules/party/party.route";
import launchpadRoute from "./modules/launchpad/launchpad.route";
import settingsRoute from "./modules/settings/settings.route";
import overviewRoute from "./modules/overview/overview.route";
import votingRoute from "./modules/voting/voting.route";
import mailerRoute from "./modules/mailer/mailer.route";
import resultsRoute from "./modules/results/results.route";
import preregisterRouter from "./modules/preregister/preregister.route";
import candidatePublicRoute from "./modules/public/candidate/candidate-public.route";
import partyPublicRoute from "./modules/public/party/party-public.route";
import homepageRoute from "./modules/public/homepage/homepage.route";
import securityRoute from "./modules/security/security.route";
import electionPublicRoute from "./modules/public/election/election-public.route";
import electionOfficerRoute from "./modules/election-officers/election-officer.route";
const router = express.Router();

router.use("/user", userRoute);
router.use("/photo", photoRoute);
router.use("/auth", authRoute);
router.use("/org", organizationRoute);
router.use("/election", electionRoute);
router.use("/candidate", candidateRoute);
router.use("/position", positionRoute);
router.use("/voter", voterRoute);
router.use("/party", partyRoute);
router.use("/launchpad", launchpadRoute);
router.use("/settings", settingsRoute);
router.use("/overview", overviewRoute);
router.use("/voting", votingRoute);
router.use("/mailer", mailerRoute);
router.use("/results", resultsRoute);
router.use("/pre-register", preregisterRouter);
router.use("/public/candidate", candidatePublicRoute);
router.use("/public/party", partyPublicRoute);
router.use("/public/homepage", homepageRoute);
router.use("/public/election", electionPublicRoute);
router.use("/security", securityRoute);
router.use("/election-officer", electionOfficerRoute);

export default router;
